# Generated by Django 6.0.2 on 2026-02-04 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="organizations.team"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="invitations", to="organizations.team"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("organization", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "organization")},
        ),
    ]
